site_name: ECE398 Weather Station Docs
site_url: https://ece398-buvip.github.io/vip-weather-docs/
repo_url: https://github.com/ece398-buvip/vip-weather-docs
theme:
  name: material

  # Font Configuration
  font:
    text: Red Hat Display
    code: Red Hat Mono
  features:
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.follow
    - toc.integrate

  favicon: images/favicon.png
  icon:
    logo: material/weather-lightning

  # Colors
  palette:
    # Dark theme
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: red
      accent: white

    # Light theme
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: red
      accent: white

# Copyright
# copyright: Copyright &copy Bradley University 2025

# Navigation
nav:
  - Home:
    - The ECE398 Weather Station: index.md
  - API Access:
    - API Access: api-access/index.md
  - Building The Station:
    - building/building.md
    - Requirements: building/requirements.md
    - Building Software: building/software-build.md
    - Wiring Diagrams: building/circuit-diagrams.md
  - For Developers:
    - Broker: developers/broker.md
    - Firmware: developers/firmware.md
    - Protocol: developers/protocol.md
    - Website: developers/website.md
  - Posts:
      - Custom RTD Board: posts/rtd-board.md
      - Battery Box Temp Measurement: posts/battery-box.md
      - Bradley-Cast Protocol (Proposed): posts/bradley-cast.md
      - ESP32-Rf Range Test: posts/esp32-rf-range.md
      - Campus Temperature Test: posts/over-campus-test.md
      - Eclipse Data: posts/ecclipse-data.md
      - Pole: posts/pole.md

# Extensions
markdown_extensions:
  - attr_list
  # Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator:
        !!python/name:material.extensions.emoji.to_svg # Code block highlighting


  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
